apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: user1-process-service-autoscale
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: DeploymentConfig
    name: user1-process-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageValue: 200m
